---
- name: "(Setup: SELinux) Install Required CentOS Dependencies"
  package:
    name: policycoreutils-python, setools
    state: present

- name: "(Setup: SELinux) Check for SELinux enabled"
  debug:
    msg: "You need to enable selinux, if it was disabled you need to reboot"
  when: ansible_selinux is undefined

- name: "(Setup: SELinux) Permissive SELinux"
  selinux:
    state: permissive
    policy: targeted
  changed_when: false
  when: ansible_selinux.mode == "enforcing"

- name: "(Setup: SELinux: Booleans) Allow HTTP network connection"
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: "(Setup: SELinux: Booleans) Allow HTTP relay connection"
  seboolean:
    name: httpd_can_network_relay
    state: yes
    persistent: yes

# - name: "(Setup: SELinux: Ports) Allow status ports"
#   seport:
#     ports: "{{ item }}"
#     proto: tcp
#     setype: http_port_t
#     state: present
#   with_items:
#     - nginx_status_port

- name: "(Setup: SELinux: Contexts) App Protect Logs"
  sefcontext:
    target: '/var/log/app_protect(/.*)?'
    setype: httpd_log_t
    state: present

- name: "(Setup: SELinux: Contexts) Apply contexts to log"
  command: restorecon -iRv /var/log/app_protect
  changed_when: false

- name: "(Setup: SELinux: Module) Create NGINX Plus Module"
  template:
    src: "{{ role_path }}/templates/selinux/nginx-plus-module.te.j2"
    dest: "{{ app_protect_tempdir }}/nginx-plus-module.te"
  register: app_protect_module

- name: "(Setup: SELinux: Module) Check NGINX Plus Module"
  command: "checkmodule -M -m -o {{ app_protect_tempdir }}/nginx-plus-module.mod {{ app_protect_tempdir }}/nginx-plus-module.te"
  args:
    creates: "{{ app_protect_tempdir }}/nginx-plus-module.mod"
  changed_when: false

- name: "(Setup: SELinux: Module) Compile NGINX Plus Module"
  command: "semodule_package -o {{ app_protect_tempdir }}/nginx-plus-module.pp -m {{ app_protect_tempdir }}/nginx-plus-module.mod"
  args:
    creates: "{{ app_protect_tempdir }}/nginx-plus-module.pp"
  changed_when: false

- name: "(Setup: SELinux: Module) Import NGINX Plus Module"  # noqa 503
  command: "semodule -i {{ app_protect_tempdir }}/nginx-plus-module.pp"
  changed_when: false
  when: app_protect_module.changed

- name: "(Setup: SELinux) Enforce SELinux"
  selinux:
    state: enforcing
    policy: targeted
  changed_when: false
  when: app_protect_selinux_enforcing and ansible_selinux.mode == "permissive"
