---
- include_tasks: "{{ role_path }}/tasks/plus/setup-{{ ansible_os_family }}.yml"
  when:
    - ansible_os_family == "Alpine"
      or ansible_os_family == "Debian"
      or ansible_os_family == "RedHat"
      or ansible_os_family == "Suse"

- name: "(Install: Linux) Install NGINX Plus"
  package:
    name: "nginx-plus{{ nginx_version | default('') }}"
    state: "{{ nginx_state }}"
  notify: "(Handler: All OSs) Start NGINX"
